mongodb:
  uri: ""
  database: ""
  timeout_secs: 30

pocket:
  start_height: 111400
  confirmations: 0
  private_key: ""
  rpc_url: ""
  chain_id: ""
  rpc_timeout_secs: 30
  fees: 10000
  multisig_address: "7FB0A18CEB4E803F22911F5B85E2727BB3BDF04B"
  multisig_public_keys:
    - "b051b20ad19432189aaea89642bf222af5c10b0c7730a374905953fd2d990715"
    - "ad7a05bb00234484531c1f379e65c4ec7e2f0feeb5e27646e193578f0fb28bb6"
    - "4294fd92033ab62cff7e49190413aa47fcb653dbfa4404fae940980bbc89227b"

pokt_monitor:
  enabled: false
  interval_secs: 120

pokt_signer:
  enabled: false
  interval_secs: 120

pokt_executor:
  enabled: false
  interval_secs: 120

ethereum:
  start_block_number: 9348824
  confirmations: 0
  private_key: ""
  rpc_url: ""
  chain_id: ""
  rpc_timeout_secs: 30
  wpokt_contract_address: "0x8E7ed40A3eF5c75485682f4f1618f079e9bd8A4E"
  mint_controller_address: "0xC2D18e34F34a9e143D8Da6F0c649a495b0D2BBd7"
  validator_addresses:
    - "0x2CE62AAF07FCE166A329D89d76588f494e39A298"
    - "0x162eFFA5a7aD26b9E1E8E70236007433270C059f"
    - "0x5272015Be727C20C40dFDDDb3Df45Fa109C102E0"

wpokt_monitor:
  enabled: false
  interval_secs: 120

wpokt_signer:
  enabled: true
  interval_secs: 120

wpokt_executor:
  enabled: false
  interval_secs: 120

logger:
  level: "debug"

health:
  interval_secs: 1800
