version: "3.8"
services:
  wpokt.mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    logging:
      driver: "none"
  wpokt.validator1:
    image: dan13ram/wpokt-validator
    build:
      context: ..
      dockerfile: ./e2e/Dockerfile
    command: "/validator --config /app/e2e/one.yml"

  wpokt.validator2:
    image: dan13ram/wpokt-validator
    build:
      context: ..
      dockerfile: ./e2e/Dockerfile
    command: "/validator --config /app/e2e/two.yml"

  wpokt.validator3:
    image: dan13ram/wpokt-validator
    build:
      context: ..
      dockerfile: ./e2e/Dockerfile
    command: "/validator --config /app/e2e/three.yml"
